MODEL:
  WEIGHT: ""
  ARCHITECTURE: "FIAN"
  CAUSAL:
    USE_CAUSALITY: True
    TAU: 16.0
    GAMMA: 0.03125
    ALPHA: 0.1
  FIAN:
    VIDEOENCODER:
      HIDDEN_DIM: 512
      ATT_WIDTH: 3
      NUM_HEADS: 4
      DROPOUT: 0.2
    QUERYENCODER:
      HIDDEN_DIM: 512
    MMENCODER:
      HIDDEN_DIM: 512
      TRANSFORMER:
        FEEDFORWARD_DIM: 512
        NUM_HEADS: 8
        DROPOUT: 0.2
    LOSS:
      TAU: 0.55
      ALPHA: 0.001
DATASETS:
  TRAIN: ("activitynet_train", )
  TEST: ("activitynet_test", )
  VISUAL_DIM: 500
  IN_MEMORY: False
  PROPOSAL_METHOD: 'sliding_window'
  WINDOW_WIDTHS: [16, 32, 64, 96, 128, 160, 192]
  WINDOW_OVERLAP: 0.75
INPUT:
  NUM_SEGMENTS: 200
  UPSAMPLE: True
  MAX_NUM_WORDS: 20
  FIX_NUM_WORDS: True
  PRE_QUERY_SIZE: 300
  WORD2VEC: 'GloVe'
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  LR: 8e-4
  BATCH_SIZE: 128
  SCHEDULER: ''
  MAX_EPOCH: 15
TEST:
  BATCH_SIZE: 128