MODEL:
  CUDNN: True
  WEIGHT: ""
  ARCHITECTURE: "CMIN"
  CAUSAL:
    USE_CAUSALITY: True
    TAU: 32.0
    GAMMA: 0.03125
    ALPHA: 0.1
  CMIN:
    HIDDEN_DIM: 512
    DROPOUT: 0.2
    QUERYENCODER:
      MAX_NUM_WORDS: 10
      NUM_GCN_LAYERS: 2
    VIDEOENCODER:
      NUM_HEADS: 4
      NUM_ATT_LAYERS: 2
      ATT_WIDTH: 3
    LOSS:
      ALPHA: 10.0
DATASETS:
  TRAIN: ("charades_train", )
  TEST: ("charades_test", )
  VISUAL_DIM: 1024
  DEP_GRAPH: True
  PROPOSAL_METHOD: 'anchor'
  ANCHOR_WIDTHS: [16, 24, 32, 40]
INPUT:
  NUM_SEGMENTS: 64
  UPSAMPLE: True
  MAX_NUM_WORDS: 10
  FIX_NUM_WORDS: True
  PRE_QUERY_SIZE: 300
  WORD2VEC: 'GloVe'
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  OPTIMIZER: 'Adam'
  LR: 4e-4
  WEIGHT_DECAY: 1e-7
  BATCH_SIZE: 64
  SCHEDULER: ''
  MAX_EPOCH: 15
  CHECKPOINT_PERIOD: 1
  TEST_PERIOD: 1
TEST:
  BATCH_SIZE: 64