MODEL:
  WEIGHT: ""
  ARCHITECTURE: "TAN"
  CAUSAL:
    USE_CAUSALITY: True
    TAU: 16.0
    GAMMA: 0.03125
    ALPHA: 0.0
  TAN:
    FEATPOOL:
      INPUT_SIZE: 1024
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 8
    FEAT2D:
      POOLING_COUNTS: [15]
    INTEGRATOR: 
      QUERY_HIDDEN_SIZE: 512
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: False
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 8
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
DATASETS:
  TRAIN: ("charades_train",)
  TEST: ("charades_test",)
  VISUAL_DIM: 1024 # We use I3D instead of VGG features
  PROPOSAL_METHOD: '2dtan'
  NUM_CLIPS: 16
INPUT:
  NUM_SEGMENTS: 128
  PRE_QUERY_SIZE: 300
  WORD2VEC: 'GloVe'
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 128
  MILESTONES: (11, 13)
  MAX_EPOCH: 15
TEST:
  NMS_THRESH: 0.45
  BATCH_SIZE: 128
