MODEL:
  CUDNN: True
  WEIGHT: ""
  ARCHITECTURE: "CSMGAN"
  CSMGAN:
    HIDDEN_DIM: 512
    DROPOUT: 0.2
    VIDEOENCODER:
      NUM_HEADS: 4
      NUM_ATT_LAYERS: 2
      ATT_WIDTH: 3
    LOSS:
      ALPHA: 0.001
      HIGH_SCORE_THR: 0.7
DATASETS:
  TRAIN: ("activitynet_train",)
  TEST: ("activitynet_test",)
  VISUAL_DIM: 500
  PROPOSAL_METHOD: 'anchor'
  ANCHOR_WIDTHS: [16, 32, 64, 96, 128, 160, 192]
INPUT:
  NUM_SEGMENTS: 200
  UPSAMPLE: True
  MAX_NUM_WORDS: 20
  FIX_NUM_WORDS: True
  PRE_QUERY_SIZE: 300
  WORD2VEC: 'GloVe'
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  OPTIMIZER: 'Adam'
  LR: 8e-4
  WEIGHT_DECAY: 1e-7
  BATCH_SIZE: 128
  SCHEDULER: ''
  MAX_EPOCH: 15
  CHECKPOINT_PERIOD: 1
  TEST_PERIOD: 1
TEST:
  BATCH_SIZE: 128