MODEL:
  WEIGHT: ""
  ARCHITECTURE: "TAN"
  TAN:
    FEATPOOL:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 4
    FEAT2D:
      POOLING_COUNTS: [15,8,8]
    INTEGRATOR:
      QUERY_HIDDEN_SIZE: 512
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: False
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 9
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
DATASETS:
  TRAIN: ("activitynet_train", )
  TEST: ("activitynet_test", )
  VISUAL_DIM: 500
  IN_MEMORY: True
  PROPOSAL_METHOD: '2dtan'
  NUM_CLIPS: 64
INPUT:
  NUM_SEGMENTS: 256
  PRE_QUERY_SIZE: 300
  WORD2VEC: 'GloVe'
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0005
  BATCH_SIZE: 32
  MILESTONES: (3, 4)
  MAX_EPOCH: 5
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 32